### ISSUE TITLE
brainstorming

### ISSUE THREAD

**Issue by ttasovac** [BCDH/exist-algolia-index#1]
Algolia //www.algolia.com is a very cool cloud-based Search API. It comes with a bunch of connectors, including Java (https://www.algolia.com/doc/guides/indexing/import-synchronize-data/java, https://github.com/algolia/algoliasearch-client-java-2), Scala etc. which are used to sync your local indexes with a remotely hosted one. Their autocomplete is really fast because their servers are distributed, and I would really like to use it for our dictionaries -- for the basic lemma autocomplete search. All the complex searches will, of course, still be handled by our Dictionary API. 

This is what my Algolia index looks like:

{
  "id": 55475,
  "norm": "дзуцнем",
  "dict": [
    "SR",
    "RGJS"
  ],
  "objectID": "55475"
}

Now, it's totally cumbersome for me to go from eXist to local MySQL and then to Alogia Index every time I add a new item to the lemma index (which is what I did just to test things out) I would love to establish a direct connection between our dictioanries (either in eXist or in our local file repository) and Algolia. 

Since Algolia is a commercial project, they charge your for every change you make to the index, so it would be very important for me to find a way of incrementally reindexing, i.e. of sending to Algolia only those lemmas that have been changed locally.

So I'm looking for an xQuery (or some other) solution that would:

1. go through our dictionary files and create a local lemma index. The first time an index is produced, it would also assign ids to each item in the index, in order to make it easier to sync with Algolia. It would then batch upload the index to Algolia. 

2. reindex our dictionaries when needed: a reindexer would go through all our dictionary files and compare current lemmas in them with the local index; only when it finds discrepancies, it would:

    a) change things in the local index (add, delete, update); and 

    b) use the Aloglia Java API to make those same changes in the remote index.

**Comment by rg-coder** [comment]
@ttasovac I have given a read about Algolia and how they work, but would like to discuss this with Adam to have his best advice. Just want to confirm from you that Algolia works on JSON, and dictionaries are in XML, so you thinking to convert them in JSON or you are keeping them natively. 

Also, the best performance is gained when there is no additional server between browser and Algolia, then where would XQuery code be coming in between what Raskovnik API is built for I suppose!

Ref: https://www.algolia.com/doc/guides/getting-started/how-it-works#introduction

![image](https://cloud.githubusercontent.com/assets/10416015/20608464/4dc46338-b2a8-11e6-9583-2e348dd1eae7.png)

**Comment by ttasovac** [comment]
Yes, we need Adam's help with this —  but in principle, the idea is to create a local JSON index based on our dictionary XML files; and then have a mechanism to incrementally upload/sync the local index with Algolia's servers using Algolia's Java API or whatever you and Adam decide is appropriate. 

We will use Algolia for the autocomplete dropdown on the frontend, nothing else. Retrieving actual entries or  advanced, complex searches will still use Raskovnik API, but the autocomplete for the simple lemma search will be based on the Algolia JSON index, on Algolia's servers. So it's a very limited use. 

Periodically, when we make changes to our dictionary files, we would need to reindex lemmas locally and then sync the local JSON index with Algolia, making sure we only upload changes to the index, rather than the whole index. 

For me, the most important thing is to make it easy for me to index, reindex and sync —  with simple commands. How the magic works (xQuery, Java etc...) remains to be decided by our guru Adam.

**Comment by rg-coder** [comment]
Did you get a chance to talk to Adam about this?

**Comment by ttasovac** [comment]
not yet. the time difference works against us :) by the way, happy belated birthday!! :)

**Comment by rg-coder** [comment]
Thanks @ttasovac.. By the way it is today.. so no belated!!
